title: Pratik Gurjar
logo: /assets/img/logo.jpeg
email: tnp.pratikgurjar@gmail.com
description: SDE @ Resultant Technologies. Java Developer.
favicon: true
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: light

google_analytics: G-2594RYWHMC

plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
  - jekyll-sitemap

platforms:
  - name: Résumé
    icon: <i class="fa-solid fa-file-lines"></i>
    link: ./assets/files/Pratik Gurjar.pdf
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/pg06pg
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/pratik-gurjar
  - name: Projects
    icon: <i class="fa-solid fa-file-code"></i>
    link: ./projects
  - name: Certifications
    icon: <i class="fa-solid fa-award"></i>
    link: ./certifications
